kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {name}-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: {sc}
  namespace: {namespace}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {sc}
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    app: {name}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
        - name: {name}
          image: {image}
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 14242
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 14242
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          volumeMounts:
            - mountPath: /var/lib/tunasync
              name: {name}-pvc
          ports:
            - name: api
              containerPort: 14242
              protocol: TCP
      volumes:
        - name: {name}-pvc
          persistentVolumeClaim:
            claimName: {name}-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {name}
  name: {name}
  namespace: {namespace}
spec:
  ports:
  - port: {port}
    protocol: TCP
    targetPort: 14242
  selector:
    app: {name}
